spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/effica
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform:
    hibernate:
      ddl-auto: update

server:
  port: 4000
  servlet:
    context-path: /api

jwt:
  secret: thelwwerk49348398rjdefndteurdhsjncjdfnemrieudiscnfmdfnwuiweudscnm3rt4grdf9